### ISSUE TITLE
Compatibility Issues with Tidy5e and Item Macro(?)

### ISSUE THREAD

**Issue by dangerdaren** [crash1115/5e-training#26] opened 2020-09-09 22:27 UTC
I love this module and have a lot of planned uses for it, but my players really like the tidy5e sheet and it seems to keep them from being able to click on the activity to roll on it. As soon as I switch to a different sheet, it works again.

In tidy5e, clicking on the activity just shows the activity’s description. I know most other items using that sheet display the description when the user clicks on a little (i) icon but let’s them roll when they click on the d20 icon.

Switching sheets to use downtime might have to be my temporary workaround, but just thought I’d let you know!

I’m running the latest stable version of Foundry in Chrome on a Mac if that’s helpful. Also just installed this module today and tidy5e sheet a few days ago so I’m pretty certain it’s all up to date.

**Comment by crash1115** [comment] 2020-09-09 22:39
Hi there! Sorry that you're having trouble, let's see if we can sort it out.

As seen in the clip below, clicking on the activity name shows the description, clicking on the d20 icon to the left of it should roll the activity. I am aware of the fact that the icon disappears when you hover over it using Tidy5e sheet, but it should still work if everything has been updated to the latest versions. 

[![Image from Gyazo](https://i.gyazo.com/e5a9277ad8536baf8c2141fe5f04d3ab.gif)](https://gyazo.com/e5a9277ad8536baf8c2141fe5f04d3ab)

Give that a try and if it still doesn't work, can you confirm that you're running the versions listed below?

- Foundry v0.6.6
- dnd5e v0.96
- Tidy5e v2.20
- Downtime v0.4.4

**Comment by dangerdaren** [comment] 2020-09-10 21:10
Hmm, I'm clicking on the d20 icon and all the version numbers match up :/ Weird. I know I have other modules installed like Combat Utility Belt, Automatic Conditions, Midi_qol and a grip of others, but it seems weird that downtime doesn't seem to be affected using the normal character sheet, only when I switch to Tidy5e.

**Comment by crash1115** [comment] 2020-09-10 22:08
It's possible that one of those other modules is clashing somehow, especially ones that change how rolls get done (mqol immediately springs to mind). If you disable _all_ your other modules does the issue persist?

If it does:
- are you getting any errors in your console? (press F12, then click on the Console tab, and look for anything red)
- Can you give me a list of all the modules you have installed?

I do not have regular access to a system with MacOS on it, but I will tomorrow, so I can try to pry into it then if I have enough information to do so.

**Comment by dangerdaren** [comment] 2020-09-11 03:05
Not seeing any particular errors (but I'm also not very conversational in code). As for modules installed... well there are a lot. You asked for 
it!


**Active Modules:**
5e Encounter Builder
About Time
Arms Reach
Autocomplete Whisper
Better NPC Sheet 5e
Better Roll Tables
Calendar/Weather
Cautious Gamemaster's Pack
Combat Utility Belt
Compendium Hider
Conditions for D&D 5e
Condition Automation
Crash's 5e Downtime Tracker
Cursor Hider
Cursor Zoom
Darker Vision for 5e
Deselection
Dice Tooltip - D&D5e
Dice Tray
Drag Upload (Get Over Here!)
DungeonDraft Importer
Dynamic Effects
Dynamic Effects SRD
EasyTable by Blitz
Favourite Item Tab
Find the Culprit
Follow Me!
Forien's Copy Environment
Forien's Custom Fonts
Forien's Unidentifies Items
Foundry Community Tables
Foundry Token Patroller
Foundry Workshop Welcome Screen
FX master
GM Notes
Health Estimate
Hide GM Rolls
Illandril's Hotbar Uses (5e)
Inventory+
Item Containers
Item Macro
Laptop Form Fix
Layer Hotkeys
Lazy Money
Less Fog
Let Me Roll That For You!
lib - Color Settings
libWrapper
Long Rest Hit Die Healing for D&D 5e
Loot Sheet NPC 5e
Magic Items
Midi QOL
Mount Up! My DND Items (Shared Compendiums)
Not Enough NPCs: A 5e NPC Generator
Permission Viewer
Pick-Up-Stix
Pin Cushion
Pings
Polyglot (I know this one doesn't work anymore)
Popout Resizer
Quick Insert
QuickSceneView
Scene Transitions
Select tool everywhere
Sheet to Token
Show Drag Distance
Show Notes
Simplefog - Manual Fog of War
Simple Name Generator
Spell Template Manager - for DnD5e
The Furnace
Tidy5e Sheet
Tidy UI - Game Settings
Token Hotbar
Token Info Icons
Token Mold
Torch
Travel Pace for D&D 5e
Trigger Happy
Turn Marker
Vance's Sidebar Resizer
Virtual Tabletop Assets - D&D Beyond Integration
Virtual Tabletop Assets - Iconizer
Virtual Tabletop Assets - Tokenizer
Whisper Box
Workshop's Ammo Swapper.

Whew! That's all of em. Most of them seem to work. A few work 70% of their full capacity. As you can see, I haven't tried to shut them down--afraid I'll lose two weeks worth of settings customizing. Is that a thing? Or do the settings stay how I made them, even when the modules are disabled and then re-enabled?

**Comment by crash1115** [comment] 2020-09-11 03:20
Haha, that's quite the list! 

Module settings should stay even between disabling/re-enabling (and generally even uninstalling and reinstalling). You can also make a backup copy of your Foundry user data folder if you'd like to play it extra safe, since that will preserve everything exactly as is.

But yeah, give it a shot with everything else disabled, see if it works then. Depending on what happens, we've got a few different routes we can take to see if we can solve the issue.

**Comment by crash1115** [comment] 2020-09-18 00:02
Discussed further with Daren over Discord, and it seems to be a problem with Item Macro. Investigating further.

**Comment by crash1115** [comment] 2020-10-07 21:06
I haven't been able to reproduce this issue. Might be an interaction between Item Macro and Tidy5e, but reasonably certain after looking at the code for all modules involved that it's not being caused by Downtime Tracking. Closing the issue for now, but if it comes up again, let me know and I'll try to dig at it harder.

**Closed as completed by crash1115** 2020-10-07 21:06 UTC
Labels: Bug
