### ISSUE TITLE
Suggestion: Ability to change icon

### ISSUE THREAD

**Issue by Ikabodo** [crash1115/5e-training#49] opened 2021-03-14 01:01 UTC
It would be nice if there was an option to change the icon from the white dice to something custom. This makes sense if there are many of them, as it makes them stand apart visually.

**Comment by crash1115** [comment] 2021-03-14 01:24
This is a dupe of #21. It'll make it into some future release, but I'm not sure when. My hands are kinda tied with RL stuff presently.

**Closed as completed by crash1115** 2021-03-14 01:24 UTC
Labels: Duplicate, Feature Request
